## Number of engines

In [1]:
N=8

## profile name

In [2]:
profile="manual_condor"

## create profile

In [3]:
%%bash -s "$profile"

profile="manual_condor"

echo $profile > .profile_name

ipython profile create --parallel --profile="$1"

[ProfileCreate] Generating default config file: '/direct/phenix+u/abagoly/.ipython/profile_manual_condor/ipython_config.py'
[ProfileCreate] Generating default config file: '/direct/phenix+u/abagoly/.ipython/profile_manual_condor/ipython_kernel_config.py'
[ProfileCreate] Generating default config file: '/direct/phenix+u/abagoly/.ipython/profile_manual_condor/ipcontroller_config.py'
[ProfileCreate] Generating default config file: '/direct/phenix+u/abagoly/.ipython/profile_manual_condor/ipengine_config.py'
[ProfileCreate] Generating default config file: '/direct/phenix+u/abagoly/.ipython/profile_manual_condor/ipcluster_config.py'


## start controllel

In [7]:
%%bash --bg --proc ipcontroller --out "/direct/phenix+u/abagoly/jupyter/logs/ipcontroller.out" -s "$profile"
export PATH="/direct/phenix+u/abagoly/jupyter/.anaconda3/bin/:$PATH"


ipcontroller --ip="*" --profile="$1"

Starting job # 3 in a separate thread.


#### kill the controller

In [6]:
ipcontroller.kill()

## start engines

In [20]:
%%bash -s "$N" "$profile"

engineLoc="/direct/phenix+u/abagoly/jupyter/.anaconda3/bin/"
lfile="/direct/phenix+u/abagoly/jupyter/logs/engine"

condor_submit condor.job -a "N=$1" -a "engineLocation=${engineLoc}"  -a "profile=$2" -a "HostName=`hostname`" \
                         -a "file=$lfile" 

Submitting job(s)........
8 job(s) submitted to cluster 1046592.


#### get engines status

In [22]:
%%bash
condor_q abagoly



-- Schedd: rcas2066.rcf.bnl.gov : <130.199.180.196:53549?...
 ID      OWNER            SUBMITTED     RUN_TIME ST PRI SIZE CMD               
1046592.0   abagoly         4/30 05:48   0+00:02:23 R  0   0.0  ipengine --profile
1046592.1   abagoly         4/30 05:48   0+00:01:05 R  0   0.0  ipengine --profile
1046592.2   abagoly         4/30 05:48   0+00:01:05 R  0   0.0  ipengine --profile
1046592.3   abagoly         4/30 05:48   0+00:01:04 R  0   0.0  ipengine --profile
1046592.4   abagoly         4/30 05:48   0+00:01:04 R  0   0.0  ipengine --profile
1046592.5   abagoly         4/30 05:48   0+00:01:04 R  0   0.0  ipengine --profile
1046592.6   abagoly         4/30 05:48   0+00:01:04 R  0   0.0  ipengine --profile
1046592.7   abagoly         4/30 05:48   0+00:01:04 R  0   0.0  ipengine --profile

8 jobs; 0 completed, 0 removed, 0 idle, 8 running, 0 held, 0 suspended


#### kill engines

In [40]:
%%bash
condor_rm abagoly

All jobs of user "abagoly" have been marked for removal


# Using the cluster

In [23]:
import numpy as np
from ipyparallel import Client

In [24]:
c = Client(profile=profile)

In [25]:
c.queue_status()

{'unassigned': 0,
 0: {'completed': 0, 'queue': 0, 'tasks': 0},
 1: {'completed': 0, 'queue': 0, 'tasks': 0},
 2: {'completed': 0, 'queue': 0, 'tasks': 0},
 3: {'completed': 0, 'queue': 0, 'tasks': 0},
 4: {'completed': 0, 'queue': 0, 'tasks': 0},
 5: {'completed': 0, 'queue': 0, 'tasks': 0},
 6: {'completed': 0, 'queue': 0, 'tasks': 0},
 7: {'completed': 0, 'queue': 0, 'tasks': 0}}

In [26]:
dv=c[:]

In [27]:
def sq(x):
    return x*x

In [28]:
v=np.linspace(0,1e8,1e7)

In [29]:
re=dv.map_async(sq, [v]*8)

In [36]:
re.status

['ok', 'ok', 'ok', 'ok', 'ok', 'ok', 'ok', 'ok']

In [37]:
re.elapsed

13.068348

In [39]:
re.get()

[array([  0.00000000e+00,   1.00000020e+02,   4.00000080e+02, ...,
          9.99999600e+15,   9.99999800e+15,   1.00000000e+16]),
 array([  0.00000000e+00,   1.00000020e+02,   4.00000080e+02, ...,
          9.99999600e+15,   9.99999800e+15,   1.00000000e+16]),
 array([  0.00000000e+00,   1.00000020e+02,   4.00000080e+02, ...,
          9.99999600e+15,   9.99999800e+15,   1.00000000e+16]),
 array([  0.00000000e+00,   1.00000020e+02,   4.00000080e+02, ...,
          9.99999600e+15,   9.99999800e+15,   1.00000000e+16]),
 array([  0.00000000e+00,   1.00000020e+02,   4.00000080e+02, ...,
          9.99999600e+15,   9.99999800e+15,   1.00000000e+16]),
 array([  0.00000000e+00,   1.00000020e+02,   4.00000080e+02, ...,
          9.99999600e+15,   9.99999800e+15,   1.00000000e+16]),
 array([  0.00000000e+00,   1.00000020e+02,   4.00000080e+02, ...,
          9.99999600e+15,   9.99999800e+15,   1.00000000e+16]),
 array([  0.00000000e+00,   1.00000020e+02,   4.00000080e+02, ...,
          9.9999