In [1]:
import numpy as np
from ipyparallel import Client

In [2]:
c = Client(profile="condor")

In [3]:
c.queue_status()

{'unassigned': 0,
 0: {'completed': 0, 'queue': 0, 'tasks': 0},
 1: {'completed': 0, 'queue': 0, 'tasks': 0},
 2: {'completed': 0, 'queue': 0, 'tasks': 0},
 3: {'completed': 0, 'queue': 0, 'tasks': 0},
 4: {'completed': 0, 'queue': 0, 'tasks': 0},
 5: {'completed': 0, 'queue': 0, 'tasks': 0},
 6: {'completed': 0, 'queue': 0, 'tasks': 0},
 7: {'completed': 0, 'queue': 0, 'tasks': 0}}

In [4]:
dv=c[:]

In [5]:
def sq(x):
    return x*x

In [6]:
v=np.linspace(0,1e8,1e7)

In [7]:
re=dv.map_async(sq, [v]*8)

In [9]:
re.status

['ok', 'ok', 'ok', 'ok', 'ok', 'ok', 'ok', 'ok']

In [10]:
re.elapsed

11.924349

In [11]:
re.get()

[array([  0.00000000e+00,   1.00000020e+02,   4.00000080e+02, ...,
          9.99999600e+15,   9.99999800e+15,   1.00000000e+16]),
 array([  0.00000000e+00,   1.00000020e+02,   4.00000080e+02, ...,
          9.99999600e+15,   9.99999800e+15,   1.00000000e+16]),
 array([  0.00000000e+00,   1.00000020e+02,   4.00000080e+02, ...,
          9.99999600e+15,   9.99999800e+15,   1.00000000e+16]),
 array([  0.00000000e+00,   1.00000020e+02,   4.00000080e+02, ...,
          9.99999600e+15,   9.99999800e+15,   1.00000000e+16]),
 array([  0.00000000e+00,   1.00000020e+02,   4.00000080e+02, ...,
          9.99999600e+15,   9.99999800e+15,   1.00000000e+16]),
 array([  0.00000000e+00,   1.00000020e+02,   4.00000080e+02, ...,
          9.99999600e+15,   9.99999800e+15,   1.00000000e+16]),
 array([  0.00000000e+00,   1.00000020e+02,   4.00000080e+02, ...,
          9.99999600e+15,   9.99999800e+15,   1.00000000e+16]),
 array([  0.00000000e+00,   1.00000020e+02,   4.00000080e+02, ...,
          9.9999